### ISSUE TITLE
resultat limité a 9

### ISSUE THREAD

**Issue by LazyGroot** [lux-lth/JobFinder#1]
Salut,

Meme quand les résultats sont supérieurs à 10 offres d'emploi il n'y a que 9 offres qui s'affichent.

Cordialement.

**Comment by lc-thomas** [comment]
Hello.
Désolé je viens de voir ton message. Je ne parviens pas à reproduire le problème, perso j'ai bien les résultats même quand il y a plusieurs pages. Tu aurais plus de détails sur le problème ?

**Comment by LazyGroot** [comment]
il y a une différence de resultat entre la recherche web et JobFinder.py et si les resultat web sont supérieur a 10, JobFinder n'en fournis jamais plus de 10.

Voici le resultat d'une requete dont le resultat ne correspond pas avec ceux du site web:
#### requete:
`python JobFinder.py -d 974 -k formateur`

#### resultat:
![capture d ecran de 2018-03-27 07-29-40](https://user-images.githubusercontent.com/33089442/37945341-c8d72912-3190-11e8-8492-1e3bd8252d28.png)
#### resultat web:
![capture d ecran de 2018-03-27 07-31-31](https://user-images.githubusercontent.com/33089442/37945377-02b67d04-3191-11e8-890e-bd61ddb55f89.png)

i

**Comment by lc-thomas** [comment]
En fait l'outil ne récupère que les résultats pour lesquels il y a une adresse email de contact.
